### ISSUE TITLE
Reference of the SS/MPC scheme

### ISSUE THREAD

**Issue by lightbulb128** [XidianNSS/NssMPClib#1]
I am looking at "FSS-DBSCAN: Outsourced Private Density-Based Clustering via Function Secret Sharing" which claims to have used this repository to implement their clustering algorithm, but the paper says its a 3-party computation. The readme claims this repo is 2-party computation instead. I wonder is there any reference paper that this repo is based on? For example, do this implementation uses OT-based (CryptFlow2) or GC-based approach for secure computation?

**Comment by jxxyh** [comment]
The main branch of our repository is mainly for 2-party computation, and we have added some 3-party computation contents in the beta branch. Currently, our library is still in the development stage, the open source part is mainly the basic operation of privacy-preserving computing, the application level can be realized based on these basic operations. The work of FSS-DBSCAN is also based on the three-party computation operations in the realization, the relevant code is still being sorted out, and has not been open-sourced yet.

**Comment by jxxyh** [comment]
This repo is mainly based on arithmetic secret sharing and function secret sharing.
There are some reference papers: 
1. ABY-A framework for effcient mixed-protocol secure two-party computation
2. ABY3: A mixed protocol framework for machine learning
3. Function secret sharing: Improvements and extensions
4. Function Secret Sharing for Mixed-Mode and Fixed-Point Secure Computation

**Comment by lightbulb128** [comment]
Understood. Thanks for your hard work!
